### ISSUE TITLE
안드로이드 스튜디오에선 어떻게 적용해야 쓸수 있나요?

### ISSUE THREAD

**Issue by mooner1022** [xeyez/StationGraph#1]
안드로이드 스튜디오에서 쓰기 위해 일주일간 삽질중인데 적용이 안됩니다. 어떻게 해야 적용할수 있나요?

**Comment by ledyx** [comment]
@mooner1022

Android Studio의 plugins 메뉴에 가서 lombok 설치하시고,

gradle dependencies에 아래 의존성을 추가하세요.

https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.8

**Comment by mooner1022** [comment]
@devwillee 
죄송하지만 하나만 더 여쭤보겟습니다.
간단한 사용방법에 적힌 코드를 그대로 실행했을때 널포인터가 뜨는데 이때에는 뭐가 문제인건가요?
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List io.github.devwillee.koreametrograph.api.MetroGraph.find(java.lang.String)' on a null object reference`
바쁘신 와중에 이것저것 질문해서 죄송합니다.

**Comment by ledyx** [comment]
@mooner1022 

죄송할 필요는 없습니다. 그냥 즐겁게 부담없이 이슈 올려주세요.

일단, gradle build 설정 파일과
해당 로그가 발생한 부분의 로그를 모두 남겨주세요.
(단, Android Studio 및 의존성에 Lombok을 제대로 설치 했다는 전제여야 합니다.)

그리고 지금 시험해보니 의존성 패키지 버전이 낮아서 실행이 안된 문제가 있었는데, 해당 부분을 갱신해서 push 했습니다.
